### ISSUE TITLE
bugfix for kitti

### ISSUE THREAD

**Issue by chengrongliang** [microsoft/MaskFlownet#10]
Hi Simon,
    some bugfix as follow.
1. reader/kitti.py: line44 and line 99
`samples = None` ->`samples =-1`;
because `samples = 32 if args.debug else -1` in main.py line194;
2. reader/kitti.py: line98 
`num_files = (len(os.listdir(path_testing)) - 1) // 2` -> `num_files = len(os.listdir(path_testing)) // 2`;
3. reader/kitti.py: line105 & line106 
`img0 = cv2.resize(img0, resize)`
`img1 = cv2.resize(img1, resize)`
->
`adj_resize = (resize[1], resize[0]) `
`img0 = cv2.resize(img0, adj_resize)` 
`img1 = cv2.resize(img1, adj_resize) `
because `cv2.resize()` should be `dim(width, height)` -> `dim(cols, rows)`

**Comment by simon1727** [comment]
Hi Rongliang, thanks a lot for bugfixing!

We will fix them in the repo soon.

**Comment by jhuxiang** [comment]
Bu it seems you haven't updated this fix in the repo.

**Comment by hellochick** [comment]
Hi @chengrongliang ,

Thanks for sharing this bug. 

I'm wondering if you can get the evaluation results of Kitti 2012/2015 as they reported in the table (e.g., 3.25, 0.11 | 9.14, 0.18 for dbbSep30) or not.

I have modified the codes and fixed the bugs, however, the calculated AEPE and F-1 are not matching.
Hope to hear from you soon.
