### ISSUE TITLE
What 512 stand for?

### ISSUE THREAD

**Issue by chengrongliang** [microsoft/MaskFlownet#12]
https://github.com/microsoft/MaskFlownet/blob/2f796ecb3255d0cdeb1a83fd2705dea08d816b27/predict.py#L64

Hi, Simon, why the `flow(:,:,1)+512`? What's the 512 stand for?

**Comment by simon1727** [comment]
Hi Rongliang,

The constant 64 and 512 comes from KITTI (how to convert our final prediction flow field to submit format for KITTI). You can find more details in the official document for KITTI dataset.

**Comment by chengrongliang** [comment]
Yes, I found that the flow values(predicted by MaskFlowNet) are much bigger than ground truth, therefore I got bad eval score. The attachment shows the difference between ground truth(frome training data) and predicted result(MaskFlowNet).
![Selection_011](https://user-images.githubusercontent.com/9505920/82188922-2dd31480-9921-11ea-8464-24eca1bc2706.jpg)


Should we judge the overflow problem? For example, `(64.0 * min((flow[:, :, 0] + 512), 512))`?

**Comment by chengrongliang** [comment]
The official document shows the value should be limited, 
```
function flow_write (F,filename)
% saves flow field F to png file
% for details see readme.txt

F = double(F);

I(:,:,1) = uint16(max(min(shiftdim(F(:,:,1))*64+2^15,2^16-1),0));
I(:,:,2) = uint16(max(min(shiftdim(F(:,:,2))*64+2^15,2^16-1),0));
I(:,:,3) = uint16(max(min(shiftdim(F(:,:,3)),1),0));
imwrite(I,filename);
```
So, I think the different between MaskFlowNet results and ground truth may be caused by overflow.
