### ISSUE TITLE
Memory curroption

### ISSUE THREAD

**Issue by rmokady** [microsoft/MaskFlownet#16]
Hi,

Your result is very impressive and. Unfortunately, I'm getting the following error:

```
*** Error in `python3': double free or corruption (!prev): 0x000055c2f1f46400 ***
Aborted
```

Did you ever encounter this type of error? or have any idea how to fix it?

Thanks

**Comment by simon1727** [comment]
Hi, thanks for your interest!

We have never encountered the same error. Maybe you should check your python environment?
