### ISSUE TITLE
A question on VCN performance in Table 1

### ISSUE THREAD

**Issue by complexfilter** [microsoft/MaskFlownet#18]
I find an inconsistency in describing the running time of VCN in Table 1 between [the arxiv paper ](https://arxiv.org/pdf/2003.10955.pdf) : 0.18 and [the official paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Zhao_MaskFlownet_Asymmetric_Feature_Matching_With_Learnable_Occlusion_Mask_CVPR_2020_paper.pdf): 0.03.

Could you let me know the exact runtime? 

Thanks!

**Comment by zsyzzsoft** [comment]
The running time of VCN in the official paper may be wrong. We later notice that its runtime is claimed to be 0.18 in the KITTI website.

**Comment by complexfilter** [comment]
> The running time of VCN in the official paper may be wrong. We later notice that its runtime is claimed to be 0.18 in the KITTI website.

Thanks for the clarification.
