### ISSUE TITLE
Details about fine-tune in the Flyingthings3D

### ISSUE THREAD

**Issue by CXMANDTXW** [microsoft/MaskFlownet#20]
Can you tell me the number of training iterations for finetune on flyings3d after pre training on flyingchairs? Would you like to use s-fine to train 0.5m iterations after flyingchairs 1.2m iterations, or restart using long + sfine for a total of 1.7m iterations?

**Comment by simon1727** [comment]
Hi,

Please see `./network/config/MaskFlownet_ft.yaml`.

**Comment by CXMANDTXW** [comment]
Thank you for your reply.I have checked this document.
In addition, I would like to ask if the file size you uploaded to MPI Sintel benchmark is the original size (436x1024)?
I found if we use the baseline model like PWC-Net, when we downsample several times, 436 will be wrong.I always use crop size(384, 1024) to test PWC-Net.

I really hope to get your help.

Best wishes

**Comment by simon1727** [comment]
We uploaded the prediction to MPI Sintel benchmark in its original size of course.

When doing inference, the size image are resize/crop to, for example, (448, 1024), since we can downsample (/2) and upsample (x2) it then.
