### ISSUE TITLE
Can you provide the .state file? 

### ISSUE THREAD

**Issue by vivasvan1** [microsoft/MaskFlownet#25]
I want to fine tune pretrained maskflownet on ChairsSDHom.
I have written the dataset scripts for it but am getting this error while training.
```
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    pipe.trainer.load_states(checkpoint.replace('params', 'states'))
  File "/home/mask/miniconda3/envs/mask/lib/python3.6/site-packages/mxnet/gluon/trainer.py", line 515, in load_states
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mask/maskflownet/MaskFlownet/weights/5adNov03-0005_1000000.states'
```

Can you please help me on how to proceed?

**Comment by vivasvan1** [comment]
Would you recommend me using the --clear_steps to avoid adding states info while starting the training?

**Comment by simon1727** [comment]
Hi vivavan1, thanks for your interest in our work.

Yes, I suggest using `--clear_steps` to reset the scheduler, and that should resolve this error :)

**Comment by vivasvan1** [comment]
Thank you it worked like a charm!
