### ISSUE TITLE
Mask visualization problem

### ISSUE THREAD

**Issue by lzh00** [microsoft/MaskFlownet#29]
I tried to visualize the mask image with the code below:
				
output = 1-(occ_mask - occ_mask.min()) / (occ_mask.max() - occ_mask.min())
io.imsave(os.path.join(seq_output_folder, fname), output)

The result is not the same with your paper claimed.
Are there any problems here?

**Comment by maximelianos** [comment]
The code is misleading - MaskFlownet model does not return occlusions. If you look at the paper, this model is composed of several MaskFlownet_S, with no occlusion output in the end (figure 2 in the paper).

Thus, occlusions can be obtained only from running MaskFlownet_S, and the results are similar to the visualization.
You don't need to use normalisation there, checking min and max shows that occlusions are in range [0, 1]. Meanwhile when I ran MaskFlownet, the output was obviously optical flow, not occlusions.

**Comment by lzh00** [comment]
@lizzardhub Thank you very much. I have tried to use MaskFlownet_S configuration and model, the output occ_mask is the same with paper claimed.

**Comment by Yugt4732** [comment]
Thanks a lot. But, how can I infer in my own data by MaskFlownet_S? 

> @lizzardhub Thank you very much. I have tried to use MaskFlownet_S configuration and model, the output occ_mask is the same with paper claimed.





> The code is misleading - MaskFlownet model does not return occlusions. If you look at the paper, this model is composed of several MaskFlownet_S, with no occlusion output in the end (figure 2 in the paper).
> 
> Thus, occlusions can be obtained only from running MaskFlownet_S, and the results are similar to the visualization.
> You don't need to use normalisation there, checking min and max shows that occlusions are in range [0, 1]. Meanwhile when I ran MaskFlownet, the output was obviously optical flow, not occlusions.
