### ISSUE TITLE
Pretrained weights on the kitti dataset for Adv attacks

### ISSUE THREAD

**Issue by jytime** [microsoft/MaskFlownet#3]
Hi authors,

I am trying to evaluate the optical flow networks' performance against attacks. I was wondering if the MaskFlownet model pretrained on the kitti dataset can be available?

Best Regards

**Comment by simon1727** [comment]
Hi, thanks for your interest!

Yes, of course, but it takes some time to rename the weight prefixes and I am having midterm right now. I will try to make it available this weekends.

**Comment by jytime** [comment]
Hi Simon,

May I ask how is it going with the renaming process?

Hope all the best.

**Comment by simon1727** [comment]
Hi, I am sorry that I was quite busy with the school things recently.

We have only done validation on the KITTI dataset for the `MaskFlownet-S`. I am wondering if that will be what you are looking for.

**Comment by jytime** [comment]
Hi Simon,

Thanks for your quick reply. I just commented to check if the model is available. It would be great if the reported MaskFlownet model can be released.

Good luck with your school things.

**Comment by simon1727** [comment]
Hi Jianyuan,

I am not sure what do you mean by _the reported MaskFlownet model_. Anyway, I have just uploaded a pretrained weights for `MaskFlownet`, called `8caNov12-1532`, which has been fine-tuned on the whole KITTI dataset.

Please run something like `python main.py MaskFlownet.yaml -g 0 -c 8caNov12 --valid --resize 576,1280` to do validation on it with inference resize `(576, 1280)`.

**Comment by jytime** [comment]
Thanks a lot, Simon
