### ISSUE TITLE
What is the variable F in your code please . . .

### ISSUE THREAD

**Issue by RokiaAbdeen** [microsoft/MaskFlownet#33]
could you please explain what should be the F in this line of code :
x2_warp = self.deform5(x2, F.repeat(F.expand_dims(flow*self.scale/self.strides[1], axis=1), 9, axis=1).reshape((0, -3, -2)))

thank you

**Comment by simon1727** [comment]
Hi Rokia,
Please search for "mxnet hybrid_forward F" for more details.

**Comment by RokiaAbdeen** [comment]
ok, thank you
