### ISSUE TITLE
confusing about FlyingThings3d dataset preload 

### ISSUE THREAD

**Issue by lelelexxx** [microsoft/MaskFlownet#4]
Hi!
    Thanks for sharing!
    When I read the code, I noticed that, seems all the training data is preloaded into RAM? and 
   when training on FlyingThings3d dataset, you have separate it into several parts, and only load one part of it during training. I didn't find the code about reload the  rest parts, Could you please point it out for me ?  Thanks again!

**Comment by simon1727** [comment]
Hi, thanks for your interest.

Yes, we load all data into RAM, and, for FlyingThings3D, you can load only a part by setting `-s` if your RAM is not enough (by default, the code loads the complete dataset). We do not implement reloading the rest parts.

**Comment by lelelexxx** [comment]
> Hi, thanks for your interest.
> 
> Yes, we load all data into RAM, and, for FlyingThings3D, you can load only a part by setting `-s` if your RAM is not enough (by default, the code loads the complete dataset). We do not implement reloading the rest parts.

I’m wonder how long it takes for training after preload data into RAM?

**Comment by simon1727** [comment]
> 
> 
> > Hi, thanks for your interest.
> > Yes, we load all data into RAM, and, for FlyingThings3D, you can load only a part by setting `-s` if your RAM is not enough (by default, the code loads the complete dataset). We do not implement reloading the rest parts.
> 
> I’m wonder how long it takes for training after preload data into RAM?

It depends on your device. When using 4 TITAN XP, it takes about two or three days for training on FlyingChairs.
