### ISSUE TITLE
Is there a pytorch implementation?

### ISSUE THREAD

**Issue by mengxiangyudlut** [microsoft/MaskFlownet#6]

**Comment by simon1727** [comment]
你好，我们没有pytorch的实现版本。

**Comment by cattaneod** [comment]
Hi @mengxiangyudlut 
I just uploaded a PyTorch porting: https://github.com/cattaneod/MaskFlownet-Pytorch

The results are slightly different from the original implementatio.
So far, only inference on KITTI is implemented, but should be easy to adapt it to other datasets.
