### ISSUE TITLE
Can I use the code to recurrent the performance reported in paper?

### ISSUE THREAD

**Issue by lelelexxx** [microsoft/MaskFlownet#8]
Hi!
     I am really interested in your paper and this repo. 
     I have trained the MaskflowNet_s using FlyingChairs dataset with the code provided in this
    repo. However, the epe on mpi-sintel clean and final is 2.999 and 4.399. There is quite a gap between the reported epe 2.88 and 4.25. 
    So, here is my question,  Is the code provided in this repo is that you used for experiment during writing the paper?  Can I use the code to recurrent the performance reported in paper without further modify? The performance reported in this paper is the best checkpoint or the final checkpoint? 
     Thanks!

**Comment by simon1727** [comment]
Hi lelelexxx, thanks again for your interest!

Yes, we believe the code provided can be used to replicate the results in the paper. The performance reported in this paper is on the last checkpoint.

The result 2.88,4.25 was obtained at the very early time among our experiments, so the code may have minor changes then. More importantly, as mentioned in [PWC-Net](https://arxiv.org/abs/1709.02371), when training on Flying Chairs dataset, the performance suffers a huge variance of as large as 0.3, so you might want to rerun it a few more times.

Hope this solves your problem.
