### ISSUE TITLE
Some problems about the prediction of optical flow and occlusion

### ISSUE THREAD

**Issue by Ecalpal** [microsoft/MaskFlownet#9]
Thanks for your great job!

When I run `python main.py MaskFlownet.yaml -g 0 -c 000Mar17 --predict`. I got outputs in **/flows**.

But it doesn't seem to be the right size.
![000000_10](https://user-images.githubusercontent.com/39435901/81763313-852c4b80-9501-11ea-851f-46ec22502e49.png)
 
The only thing I changed in the code was to replace **imread** in **skimage.io** with **imread** in **cv2**.
https://github.com/microsoft/MaskFlownet/blob/2f796ecb3255d0cdeb1a83fd2705dea08d816b27/reader/sintel.py#L3

My environment:
python 3.6.8
mxnetcu90-1.5.1
CUDA 9.0.176
cudnn 7.6.5

In addition, I would like to ask how to correctly visualize occlusion in binary form?

**Comment by chengrongliang** [comment]
please refer to https://github.com/microsoft/MaskFlownet/issues/10

**Comment by Ecalpal** [comment]
> @Ecalpal please refer to #10

It works! Thanks a lot!

**Comment by simon1727** [comment]
Hi Ecalpal, thanks for your interest in our project.

Yes, as Rongliang stated, there are bugs in our code for KITTI dataset now. We will fix them soon.

Again, thanks @chengrongliang for giving the bugfix!

**Comment by Ecalpal** [comment]
> Hi Ecalpal, thanks for your interest in our project.
> 
> Yes, as Rongliang stated, there are bugs in our code for KITTI dataset now. We will fix them soon.
> 
> Again, thanks @chengrongliang for giving the bugfix!

Is there any way to binary the  occ_mask? Because the way of binarization in each paper is different, I want to know your binarization method.
